# Pandas

## why pandas

- Easy to use
- consistent with other modules 
- Essential skill to be hired 

## What is pandas used for 

- loading data
- Data cleansing
- Data preprocessing and normalization
- Merges and Joins
- Data visualisation
- Statistical analysis
- Data inspection
- etc.

# Pandas Data structures 
- Pandas Series 
- Pandas Data Frame

### Pandas series and pandas DataFrame are constructed on the top of  numpy Array which makes them fast

## Pandas series

- one dimensional array like structure ( one column)
- Heterogeneous ( which means that can contain various type of data)

In [24]:
import pandas as pd

In [25]:
pd.__version__ # verfiy the version of pandas

'2.2.1'

In [26]:
s1=pd.Series()
s1

Series([], dtype: object)

In [27]:
s2=pd.Series([1,2,3,4,5])
s2 # creating a serie of number between 1 to 5

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [28]:
s2.index # extracting the range of index 

RangeIndex(start=0, stop=5, step=1)

In [29]:
s2.values # extracting values 

array([1, 2, 3, 4, 5], dtype=int64)

In [30]:
s3=pd.Series([1,2,3,4,5], index= [10,20,30,40,50])
s3  # creating a serie and assigning index 

10    1
20    2
30    3
40    4
50    5
dtype: int64

In [31]:
scores=pd.Series([3.2,4.5,2.6,5,4], index=["Bob","Claudia","Aline","Kenzo", "Arnauld"])
scores

Bob        3.2
Claudia    4.5
Aline      2.6
Kenzo      5.0
Arnauld    4.0
dtype: float64

In [32]:
scores.index

Index(['Bob', 'Claudia', 'Aline', 'Kenzo', 'Arnauld'], dtype='object')

In [15]:
scores.values

array([3.2, 4.5, 2.6, 5. , 4. ])

In [45]:
### converting  a dictionary into a serie

StudentScores={'Bob':3.2, 'Claudia':4.5, 'Aline':2.6, 'Kenzo':5, 'Arnauld': 3.8}
s4=pd.Series(StudentScores)
s4

Bob        3.2
Claudia    4.5
Aline      2.6
Kenzo      5.0
Arnauld    3.8
dtype: float64

In [34]:
s4.index

Index(['Bob', 'Claudia', 'Aline', 'Kenzo', 'Arnauld'], dtype='object')

In [35]:
s4.values

array([3.2, 4.5, 2.6, 5. , 3.8])